name: Prepare Release
description: Prepares the release by parsing the version and setting it as an output variable.

inputs:
  version:
    description: "The parsed version from the tag name."
    required: true
    default: ""
  artifact_prefix:
    description: "The prefix for the release artifacts."
    required: false
    default: "release-jars"
  java_version:
    description: "The Java version to use for the release preparation."
    required: false
    default: "21"
  java_distribution:
    description: "The Java distribution to use for the release preparation."
    required: false
    default: "temurin"
  token:
    description: "The GitHub token to use for authentication when uploading artifacts."
    required: true
    default: ""
  file-glob-pattern:
    description: "The glob pattern to match the files to be uploaded as release assets."
    required: false
    default: "output/*.jar"
  tag_name:
    description: "The tag name to parse the version from."
    required: true

runs:
  using: composite
  steps:
    - name: Project Setup
      uses: matthiesen-dev/automation/.github/actions/java-project-setup@main
      with:
        java_version: ${{ inputs.java_version }}
        java_distribution: ${{ inputs.java_distribution }}

    - name: Build with Gradle
      shell: bash
      run: ./gradlew build
      env:
        RELEASE_VERSION: ${{ inputs.version }}

    - name: Copy and Upload Release Assets
      uses: matthiesen-dev/automation/.github/actions/copy-upload-release-assets@main
      with:
        version: ${{ inputs.version }}
        artifact_prefix: ${{ inputs.artifact_prefix }}
        token: ${{ inputs.token }}
        file-glob-pattern: ${{ inputs.file-glob-pattern }}
        tag_name: ${{ inputs.tag_name }}
