name: Publish Modrinth Singleloader Release

on:
  workflow_call:
    inputs:
      artifact_prefix:
        description: "The prefix for the release artifacts."
        required: false
        type: string
        default: "release-jars"

      artifact_basename:
        description: "The base name for the release artifacts (without loader and version)."
        required: true
        type: string

      mod_name:
        description: "The name of the mod to publish."
        required: true
        type: string
      version:
        description: "The version to publish."
        required: true
        type: string
        default: ""
      changelog:
        description: "The changelog to include in the Modrinth release."
        required: true
        type: string
        default: ""

      loader:
        description: "The loader to target for this release (e.g., fabric, neoforge)."
        required: true
        type: string

      modrinth_game_version:
        description: "The game version to target on Modrinth."
        required: true
        type: string
      modrinth_dependencies:
        description: "The dependencies to set for the Modrinth release (in JSON format)."
        required: false
        type: string
        default: "[]"

      modrinth_id:
        description: "The Modrinth project ID to publish to."
        required: true
        type: string

      readme_path:
        description: "The path to the README file to use for the Modrinth description."
        required: false
        type: string
        default: "README.md"

      modrinth_publish_files:
        description: "The glob pattern for the files to publish to Modrinth (relative to the artifact download path)."
        required: false
        type: string

    secrets:
      MODRINTH_TOKEN:
        description: "The Modrinth API token to use for authentication."
        required: true

jobs:
  publish_modrinth:
    runs-on: ubuntu-latest
    steps:
      - name: Parsed Files glob
        id: parsed_files
        run: |
          if [[ -n "${{ inputs.modrinth_publish_files }}" ]]; then
            echo "files=${{ inputs.modrinth_publish_files }}" >> $GITHUB_OUTPUT
          else
            echo "files=output/${{ inputs.artifact_basename }}-${{ inputs.loader }}-${{ inputs.version }}.jar" >> $GITHUB_OUTPUT
          fi

      - name: Download Release Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_prefix }}-${{ inputs.version }}
          path: output

      - name: Publish ${{ inputs.loader }} to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ inputs.modrinth_id }}
          name: ${{ format('{0} {1} - {2}', inputs.mod_name, inputs.version, inputs.loader) }}
          version: ${{ inputs.version }}
          changelog: ${{ inputs.changelog }}
          loaders: ${{ inputs.loader }}
          game-versions: ${{ inputs.modrinth_game_version }}
          files: ${{ steps.parsed_files.outputs.files }}
          dependencies: ${{ inputs.modrinth_dependencies }}

  sync_description_modrinth:
    needs: publish_modrinth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Sync Modrinth Description
        uses: funnyboy-roks/modrinth-auto-desc@v1.7
        with:
          auth-token: ${{ secrets.MODRINTH_TOKEN }}
          slug: ${{ inputs.modrinth_id }}
          readme: ${{ inputs.readme_path }}
