name: Publish Modrinth Multiloader Release

on:
  workflow_call:
    inputs:
      artifact_basename:
        description: "The base name for the release artifacts (without loader and version)."
        required: true
        type: string
      mod_name:
        description: "The name of the mod to publish."
        required: true
        type: string
      version:
        description: "The version to publish."
        required: true
        type: string
        default: ""
      changelog:
        description: "The changelog to include in the Modrinth release."
        required: true
        type: string
      modrinth_game_version:
        description: "The game version to target on Modrinth."
        required: true
        type: string
      modrinth_id:
        description: "The Modrinth project ID to publish to."
        required: true
        type: string

      artifact_prefix:
        description: "The prefix for the release artifacts."
        required: false
        type: string
        default: "release-jars"
      modrinth_dependencies:
        description: "The dependencies to set for the Modrinth release (in JSON format)."
        required: false
        type: string
        default: "[]"
      modrinth_fabric_dependencies:
        description: "The dependencies to set for the Modrinth release (in JSON format) for Fabric loader."
        required: false
        type: string
        default: "[]"
      modrinth_neoforge_dependencies:
        description: "The dependencies to set for the Modrinth release (in JSON format) for NeoForge loader."
        required: false
        type: string
        default: "[]"
      readme_path:
        description: "The path to the README file to use for the Modrinth description."
        required: false
        type: string
        default: "README.md"
      copy_file_outdir:
        description: "The directory to copy the published files to after publishing (relative to the artifact download path)."
        required: false
        type: string
        default: "output"
    secrets:
      MODRINTH_TOKEN:
        description: "The Modrinth API token to use for authentication."
        required: true

jobs:
  publish_modrinth:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - loader: "fabric"
            name_suffix: "Fabric"
          - loader: "neoforge"
            name_suffix: "NeoForge"
    steps:
      - name: Determine Dependencies for ${{ matrix.name_suffix }}
        id: determine_dependencies
        uses: matthiesen-dev/automation/.github/actions/determine-dependencies@main
        with:
          base_dependencies: ${{ inputs.modrinth_dependencies }}
          extra_dependencies: ${{ matrix.loader == 'fabric' && inputs.modrinth_fabric_dependencies || matrix.loader == 'neoforge' && inputs.modrinth_neoforge_dependencies || '[]' }}

      - name: Download Release Artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact_prefix }}-${{ inputs.version }}
          path: ${{ inputs.copy_file_outdir }}

      - name: Publish ${{ matrix.name_suffix }} to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ inputs.modrinth_id }}
          name: ${{ format('{0} {1} - {2}', inputs.mod_name, inputs.version, matrix.name_suffix) }}
          version: ${{ inputs.version }}
          changelog: ${{ inputs.changelog }}
          loaders: ${{ matrix.loader }}
          game-versions: ${{ inputs.modrinth_game_version }}
          files: ${{ inputs.copy_file_outdir }}/${{ inputs.artifact_basename }}-${{ matrix.loader }}-${{ inputs.version }}.jar
          dependencies: ${{ steps.determine_dependencies.outputs.merged_dependencies }}

  sync_description_modrinth:
    needs: publish_modrinth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Sync Modrinth Description
        uses: funnyboy-roks/modrinth-auto-desc@v1.7
        with:
          auth-token: ${{ secrets.MODRINTH_TOKEN }}
          slug: ${{ inputs.modrinth_id }}
          readme: ${{ inputs.readme_path }}
